name: My main test action
run-name: My main test action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: elizabethtl/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Use OZI publish
        uses: OZI-Project/publish@v1.13.2
